# Site settings
title: 
email: jeffmcaffer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jeff McAffer on open source, Microsoft, and maybe even car racing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mcaffer.com" # the base hostname & protocol for your site
twitter_username: jeffmcaffer
github_username:  jeffmcaffer

# Build settings
markdown: kramdown
highlighter: rouge
